---
name: Visual Studio Bug report
description: Create a report to help us improve the Reqnroll Visual Studio Extension
body:
- type: dropdown 
  attributes:
    label: Used Visual Studio
    options:
      - Visual Studio 2022
      - Visual Studio 2026
  validations:
    required: true
- type: dropdown
  attributes:
    label: Are the latest Visual Studio updates installed?
    options:
      - 'Yes'
      - 'No'
  validations:
    required: true
- type: textarea
  attributes:
    label: Content of reqnroll.json (if present)
    placeholder: PLEASE COPY THE ENTIRE reqnroll.json
- type: textarea
  attributes:
    label: Issue Description
  validations:
    required: true
- type: textarea
  attributes:
    label: Steps to Reproduce
  validations:
    required: true
- type: input
  attributes:
    label: Link to a project repository that reproduces the issue
  validations:
    required: false
